version = 0.1
[default.deploy.parameters]
stack_name = "respondio-test"
resolve_s3 = true
s3_prefix = "respondio-test"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
disable_rollback = true
image_repositories = []
